trigger:
  branches:
    include:
    - '*'

pr:
- master

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    Python35:
      python.version: '3.5'
    Python36:
      python.version: '3.6'
    Python37:
      python.version: '3.7'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install .
    pip install -r ci-requirements.txt

    sudo npm i -g vsce # Tests requirements
  displayName: 'Install dependencies'

- script: |
    black --check textx_gen_vscode
    black --check tests
  displayName: 'black'
  condition: eq(variables['python.version'], '3.6')

- script: |
    bandit -c .bandit -r textx_gen_vscode
  displayName: 'bandit'

- script: |
    pytest tests/ --cov textx_gen_vscode --cov-report html
  displayName: 'pytest and coverage'
